### ISSUE TITLE
Application stopped

### ISSUE THREAD

**Issue by ulamnet** [OhMyLob/MusicShare#1]
Hello , my phone model ; sony xperia c5 ultra , and android version ; 5.1.1 , ı install this app from play store but when ı want get a login application stopped.

Thanks.

**Comment by OhMyLob** [comment]
Hello! Thanks for having opened this issue. The fix will be included in the next version (it'll be released very soon). 😄

**Comment by ulamnet** [comment]
thanks for feedback , I have a one question , how to get a artists ?

**Comment by OhMyLob** [comment]
You mean search people by artist?

**Comment by ulamnet** [comment]
search musicians.

**Comment by ulamnet** [comment]
Actually , good will How does video for this app...Beacuse this app look like very cool.

**Comment by OhMyLob** [comment]
Uhmm...this app is about searching people, not artists...

**Comment by ulamnet** [comment]
Auh..So how to add , share music with this app ?

**Comment by OhMyLob** [comment]
Music is automatically uploaded to your profile.

**Comment by ulamnet** [comment]
I mean how to share music with friends ?

**Comment by OhMyLob** [comment]
Your friends can download Music Share and follow you to see what you are listening to.

**Comment by ulamnet** [comment]
my english bad , sorry :) so friends how to see who listen music?

**Comment by OhMyLob** [comment]
No problem 😃 
Your friends can download on your profile (searching your name) and see who you're listening to. See screenshots on Google Play, maybe they can make you understand.

**Comment by ulamnet** [comment]
ı understand your part , but ı mean users how to add music ? for friends see music in profile.

**Comment by OhMyLob** [comment]
Music is automatically added to your profile

**Comment by ulamnet** [comment]
according to what?

**Comment by OhMyLob** [comment]
When you start playing a song with your music player, the app will add the song in your profile.

**Comment by ulamnet** [comment]
Okay , finally understand :) :+1:

**Comment by OhMyLob** [comment]
Awesome! 😄

**Comment by ulamnet** [comment]
what about think when fix this issue beacuse ı really ı need a this cool app! :)

**Comment by OhMyLob** [comment]
I'm publishing the app right now

**Comment by ulamnet** [comment]
I waiting , thanks :)!

**Comment by OhMyLob** [comment]
Thanks to you! 👍

**Comment by ulamnet** [comment]
![ekran alintisi](https://cloud.githubusercontent.com/assets/583003/14588089/61cbc9d0-04c9-11e6-8b2f-ec6d4f2239f9.PNG)

I see in android studio this error.

**Comment by ulamnet** [comment]
Sorry for closed wrong click.
