### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by ulamnet** [OhMyLob/MusicShare#2]
Hey ,it's me again... In android studio ı get this error .How to fix?
![ekran alintisi](https://cloud.githubusercontent.com/assets/583003/14588236/ba58415c-04cc-11e6-9f4d-551dfe846b1f.PNG)

**Comment by ulamnet** [comment]
I try apk file and app not opened.

**Comment by ulamnet** [comment]
And still app stopped.

**Comment by OhMyLob** [comment]
Try to clean reinstall the app

**Comment by ulamnet** [comment]
Ok working on android studio but , ı try my phone but still error.

**Comment by OhMyLob** [comment]
So you've already tried uninstalling and reinstalling the app on the phone?

**Comment by ulamnet** [comment]
yes. still this error : sorry musicshare stopped.

**Comment by OhMyLob** [comment]
Mmh could you tell me your email please?

**Comment by ulamnet** [comment]
kimmodacom@gmail.com

**Comment by ulamnet** [comment]
Are you there?

**Comment by ulamnet** [comment]
This app In android version 5.1 get a error.

**Comment by OhMyLob** [comment]
Can we continue via Telegram or Hangouts please?

**Comment by ulamnet** [comment]
maybe hangouts

**Comment by OhMyLob** [comment]
Ok thanks, contact me on Hangouts please.

**Comment by ulamnet** [comment]
what is your adress ?
